# Generated by Django 4.2.11 on 2024-07-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images255/')),
                ('description', models.TextField()),
                ('scientific_name', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('collection_date', models.DateField()),
            ],
        ),
    ]
