# Generated by Django 4.2.11 on 2024-07-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('H_backend', '0002_newplant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newplant',
            name='scientific_name',
        ),
    ]
