# Generated by Django 4.2.11 on 2024-07-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('H_backend', '0003_remove_newplant_scientific_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newplant',
            name='collection_date',
        ),
    ]
