# Generated by Django 4.1.5 on 2024-07-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H_backend', '0004_remove_newplant_collection_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('family', models.CharField(max_length=255)),
                ('genus', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('collection_date', models.DateField()),
                ('collected_by', models.CharField(max_length=255)),
            ],
        ),
    ]
